Move most dependencies to `extra_requires` except bare-minimum deps
abhiTronix/vidgear pull request #268
Opened 2021-11-23 15:15 UTC by zpapakipos

## Description
I modified the `setup.py` file by moving most of the dependencies in `install_requires` to separate `extra_requires`. This will lighten the installation process for most users as they can only install the dependencies needed for the parts of the `vidgear` API that they will use. Some example usages will look like the following:
```
pip install vidgear  # installs bare-minimum deps
```
```
pip install vidgear[camgear]  # installs bare-minimum + deps needed for camgear API
```
```
pip install vidgear[netgear, asyncio]  # installs bare-minimum + deps needed for netgear & asyncio APIs
```

@abhiTronix can you please checkout this branch, test installing & building the wheel using this version of the `setup.py`, and once you verify it's working upload a new version of `vidgear` to pypi so that we can install using these bare-minimum deps? Thanks! :)

### Requirements / Checklist

- [x] I have read the [PR Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/PR/#submitting-pull-requestpr-guidelines).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [x] I have updated the documentation accordingly(if required).

### Related Issue

https://github.com/abhiTronix/vidgear/issues/267

### Context

As I said above, this will lighten the installation process for most users as they can only install the dependencies needed for the parts of the `vidgear` API that they will use. For us for example this will unblock us so we are able to install the bare-minimum `vidgear` in our codebase which is already quite heavy (so installing unnecessary deps is a pain).

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Screenshots (if available):

2021-11-23 17:23 UTC, abhiTronix commented
@zpapakipos Sorry but you have to change base branch from `master` to `testing` branch(as mentioned in our [contribution guidelines](https://abhitronix.github.io/vidgear/latest/contribution/PR/#clone-testing-branch)), as we don't allow changes directly into `master` branch. Then only we can work with it.

See this doc https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request for doing it easily,

2021-11-23 17:39 UTC, zpapakipos commented
@abhiTronix done!

2021-11-23 17:42 UTC, zpapakipos commented
@abhiTronix I resolved the merge conflicts -- it looks like in the testing branch the `colorlog` dependency had been modified so it required the most recent version. I don't think this should be necessary, so I removed that change. Let me know if there is some reason `colorlog` needs to be **the most recent** version for `vidgear` to run. This would complicate things a lot on our side.

2021-11-23 17:56 UTC, abhiTronix commented
> @abhiTronix I resolved the merge conflicts

@zpapakipos Thank you again.

>   it looks like in the testing branch the colorlog dependency had been modified so it required the most recent version. I don't think this should be necessary, so I removed that change. Let me know if there is some reason colorlog needs to be the most recent version for vidgear to run.

No, The recent version is added to colorlog just to include more notable changes in its latest release which provide better formatting.

> This will lighten the installation process for most users as they can only install the dependencies needed for the parts of the vidgear API that they will use. Some example usages will look like the following:
pip install vidgear  # installs bare-minimum deps
pip install vidgear[camgear]  # installs bare-minimum + deps needed for camgear API
pip install vidgear[netgear, asyncio]  # installs bare-minimum + deps needed for netgear & asyncio APIs

I think this will complicate installation for everyday user. In my opinion,  the correct way to do this is to bundling all API specific dependencies under one name such as "core" and also providing same dependencies under "asyncio" as well(since `extra_requires` doesn't share dependencies in different names) along with its specific dependencies. So final configrations would be:

```sh
pip install vidgear  # installs bare-minimum deps
pip install vidgear[core]  # installs bare-minimum deps + API specific deps
pip install vidgear[asyncio]  # installs bare-minimum deps + API specific deps + Asyncio deps
```

2021-11-23 18:01 UTC, abhiTronix commented
Also we don't need recent version for all deps, it's for selected ones that need updation more frequently for its working properly like `yt_dlp`. But leave it, as I'll correct it later.

2021-11-23 22:02 UTC, zpapakipos commented on setup.py
> +        "screengear": [
```suggestion
        "core": [
            "pafy{}".format(latest_version("pafy")),
            "yt_dlp{}".format(latest_version("yt_dlp")),  # pafy backend
            "streamlink",
            "pyzmq{}".format(latest_version("pyzmq")),
            "simplejpeg{}".format(latest_version("simplejpeg")),
```

2021-11-23 22:02 UTC, zpapakipos commented on setup.py
> +            "starlette{}".format(latest_version("starlette")),
```suggestion
            "pafy{}".format(latest_version("pafy")),
            "yt_dlp{}".format(latest_version("yt_dlp")),  # pafy backend
            "streamlink",
            "pyzmq{}".format(latest_version("pyzmq")),
            "simplejpeg{}".format(latest_version("simplejpeg")),
            "mss{}".format(latest_version("mss")),
            "Pillow",
            "pyscreenshot{}".format(latest_version("pyscreenshot")),
            "starlette{}".format(latest_version("starlette")),
```

2021-11-23 22:07 UTC, zpapakipos commented
> I think this will complicate installation for everyday user. In my opinion, the correct way to do this is to bundling all API specific dependencies under one name such as "core" and also providing same dependencies under "asyncio" as well(since extra_requires doesn't share dependencies under different names) along with its own dependencies.

This sounds good to me! I made the change to this branch, please take a look & let me know if it looks good :)

> No, The recent version is added to colorlog just to include more notable changes in its latest release which provide better formatting.

I see. Is it ok with you if we put just `colorlog` in the base requirements and then if people want to have the most up-to-date log formatting they can choose to update `colorlog` themselves? Or alternatively you could put `colorlog` with the most recent version in the `core` requirement extra, but only `colorlog` in the base requirements. For example for us, we don't want to have to install a whole new version of `colorlog` just so we can install `vidgear` in our internal codebase (we already have 3.1.4 installed, which is old but works fine for our use case).

2021-11-24 02:56 UTC, abhiTronix commented
> I see. Is it ok with you if we put just colorlog in the base requirements and then if people want to have the most up-to-date log formatting they can choose to update colorlog themselves? Or alternatively you could put colorlog with the most recent version in the core requirement extra, but only colorlog in the base requirements. For example for us, we don't want to have to install a whole new version of colorlog just so we can install vidgear in our internal codebase (we already have 3.1.4 installed, which is old but works fine for our use case).

@zpapakipos Sounds good to me. 👍🏽 

I've suggested few changes above, make sure to commit them as well, and also don't worry above test failing as they're caused by old `pafy` dependency that's subjected to replaced/removed soon.

2021-11-24 09:06 UTC, zpapakipos commented
I don't see any changes you suggested. Can you comment on the code with any changes? Then I'm happy to add them.

Also, once this is landed how soon do you plan to release v0.2.4? For our use it would be great to have the new version in the next week, is that possible?

2021-11-24 10:19 UTC, abhiTronix commented
> I don't see any changes you suggested. Can you comment on the code with any changes? Then I'm happy to add them.

@zpapakipos See reviews left on the code above:
![image](https://user-images.githubusercontent.com/34266896/143219776-46c23191-b5d4-42fe-9423-64dfc8f2e797.png)

2021-11-24 10:20 UTC, abhiTronix commented
> Also, once this is landed how soon do you plan to release v0.2.4? For our use it would be great to have the new version in the next week, is that possible?

Very much possible, but I first need to update docs and replace `pafy` dependency.

2021-11-24 10:22 UTC, abhiTronix requested changes
@zpapakipos Please make these changes.

2021-11-24 10:22 UTC, abhiTronix commented on setup.py
> +    + (["picamera"] if ("arm" in platform.uname()[4][:3]) else []),
Hi @zpapakipos, Move `picamera` to `extra_requires` as it's specific only to PiGear API.

2021-11-24 10:22 UTC, abhiTronix commented on setup.py
> +        ),
Also @zpapakipos, We can Introduce [PEP 508](https://www.python.org/dev/peps/pep-0508/) here:

```python
+ ["uvloop > 0.14.0; (platform_system!='Windows'" and python_version >= "3.7") ]
+ ["uvloop == 0.14.0; (platform_system!='Windows'" and python_version == "3.6") ]
```

2021-11-24 18:12 UTC, zpapakipos commented on setup.py
> +    + (["picamera"] if ("arm" in platform.uname()[4][:3]) else []),
```suggestion
```

2021-11-24 18:23 UTC, zpapakipos commented on setup.py
> +        ]
```suggestion
        ]
        + (["picamera"] if ("arm" in platform.uname()[4][:3]) else []),
```

2021-11-24 18:24 UTC, zpapakipos commented on setup.py
> +        ],
```suggestion
        ]
        + (["picamera"] if ("arm" in platform.uname()[4][:3]) else []),
```

2021-11-24 18:25 UTC, zpapakipos commented on setup.py
> +        ),
Sorry, I'm not sure exactly where you want this -- can you add it as a suggestion & commit it to add to this branch yourself? I added the rest so let me know if they look good!

2021-11-24 18:26 UTC, zpapakipos commented
> Very much possible, but I first need to update docs and replace `pafy` dependency.

Super glad to hear this, thanks! :)

I made/replied to all your changes, let me know if it looks good!

2021-11-25 01:36 UTC, abhiTronix commented on setup.py
> +        ),
@zpapakipos Sure.

2021-11-25 01:38 UTC, abhiTronix approved these changes
LGTM!

2021-11-25 01:48 UTC, merged

2021-11-25 08:36 UTC, zpapakipos commented
Awesome, thanks for the quick turnaround time! :) Looking forward to vidgear v0.2.4 with these changes!

2021-12-05 13:08 UTC, abhiTronix commented
@zpapakipos  **The latest vidgear `v0.2.4` is now available on pypi with this fix: https://pypi.org/project/vidgear/**. Goodluck 👍🏽