SS: Dash Segments Videos are not supported by OpenCV VideoCapture.
abhiTronix/vidgear pull request #313
Opened 2022-06-16 12:15 UTC by DynamiteC

## Brief Description
# Ignoring a Video Protocol not supported by OpenCV

Just continuing the loop when stream protocol is of http_dash_segments.
`                
if stream_protocol == 'http_dash_segments':
                    continue
`

### Requirements / Checklist

- [x] I have read the [PR Guidelines](https://abhitronix.github.io/vidgear/latest/contribution/PR/#submitting-pull-requestpr-guidelines).
- [x] I have read the [Documentation](https://abhitronix.github.io/vidgear/latest).
- [ ] I have updated the documentation accordingly(if required).

### Context

I was working on reading frames from youtube when the source URL sometimes failed so I checked, and found that when it failed was solely due to the URL was not supported by OpenCV so resolved that by just continuing the loop in case of HTTP DASH Segments Video

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Screenshots (if available):

![Screenshot from 2022-06-16 12-14-03](https://user-images.githubusercontent.com/19831283/174067405-49315d89-7d65-453d-85ca-658c8bc87e70.png)

2022-06-16 12:53 UTC, abhiTronix commented
@DynamiteC Thanks for the PR, this is a long pending issue. I'll test it locally and let you know.

2022-06-16 13:10 UTC, DynamiteC commented
Okay will do, sorry for that.

2022-06-16 13:17 UTC, DynamiteC commented
Is this correct now?

2022-06-16 13:20 UTC, DynamiteC commented
Now updated, didnt changed from below options. sorry for so many commits.

2022-06-16 13:24 UTC, DynamiteC commented
> @DynamiteC Ok leave it, just a bit hard to see changes. No worries I'll change it after merge(if accepted).

Alright!

2022-06-17 00:55 UTC, abhiTronix requested changes
@DynamiteC Remove your code and place it in the required `if` logic.

2022-06-17 00:55 UTC, abhiTronix commented on vidgear/gears/camgear.py
> +                    continue
@DynamiteC Remove this code:
```py
                if stream_protocol == 'http_dash_segments':
                    continue
```

2022-06-17 00:55 UTC, abhiTronix commented on vidgear/gears/camgear.py
> +                if stream_with_video and stream_dim and stream_url:
@DynamiteC Put the code here by changing following logic:

```py
                if stream_with_video and stream_dim and stream_url:
```

to

```py
                if stream_with_video and stream_dim and stream_url and stream_protocol != "http_dash_segments":
```

2022-06-17 01:11 UTC, DynamiteC commented on vidgear/gears/camgear.py
> +                    continue
Done.

2022-06-17 01:11 UTC, DynamiteC commented on vidgear/gears/camgear.py
> +                if stream_with_video and stream_dim and stream_url:
Done

2022-06-17 01:16 UTC, abhiTronix commented
@DynamiteC Thanks, LGTM!

2022-06-17 01:18 UTC, abhiTronix approved these changes
Changes are approved. I'll merge after CI tests are completed.

2022-06-17 01:21 UTC, DynamiteC commented
Alright thanks, i forgot that you follow double quotes so I had to make another comit for that. thank you!!

2022-06-17 01:44 UTC, abhiTronix commented
> Alright thanks, i forgot that you follow double quotes so I had to make another comit for that. thank you!!

Generally you must avoid single quotes for text in Python, as they're used for anything that behaves like an Identifier.

2022-06-17 03:58 UTC, DynamiteC commented
Thank you, I will keep that in mind. I still learning python. If you have any recommendations on where to get advanced on python then please do. Thanks a lot!

2022-06-17 04:54 UTC, merged